version: '3.3'
services:
  redis:
    image: redis:latest
    ports:
      - 127.0.0.1:${REDIS_PORT:-6379}:6379
    networks:
      - texlive-network
    volumes:
      - redis_data:/data
    restart: always

  apt-web:
    restart: always
    build: .
    image: swiftlatex/apt
    container_name: apt
    ports:
      - ${PORT:-5000}:${PORT:-5000}
    environment:
      - PORT=${PORT:-5000}
      - REDIS_URL=redis://redis:6379
      - API_ORIGINS=${API_ORIGINS:-}
      - HOST_DOMAIN=${HOST_DOMAIN:-}
    networks:
      - texlive-network
    depends_on:
      - redis
    env_file:
      - .env

networks:
  texlive-network:
    driver: bridge

volumes:
  redis_data: